version: 2.1

orbs:
  go: circleci/go@1.7.1

executors:
  linux:
    docker:
      - image: golang:1.18

  macos:
    macos:
      xcode: 13.3.1

jobs:
  build-binary:
    executor: linux
    steps:
    - checkout
    - run: apt-get update
    - run: apt-get install --yes awscli
    - run: make upload-release-binary TARGET_ARCH=amd64
    - run: make upload-release-binary TARGET_ARCH=arm64
    - run: make upload-release-binary TARGET_OS=windows TARGET_ARCH=amd64
    - run: make upload-release-binary TARGET_OS=windows TARGET_ARCH=arm64
    - run: make upload-release-binary TARGET_OS=windows TARGET_ARCH=386

  build-universal-binary:
    executor: macos
    steps:
    - checkout
    - go/install:
        version: "1.18"
    - run: brew install awscli || true
    - run: make upload-release-binary-universal

workflows:
  all-binaries:
    when:
      equal: [ << pipeline.git.branch >>, 'circleci' ]

    jobs:
    - build-binary
    - build-universal-binary