version: 2.1

orbs:
  go: circleci/go@1.7.1

executors:
  linux:
    machine:
      image: ubuntu-2004:202201-02

  macos:
    macos:
      xcode: 13.3.1

jobs:
  build-binary:
    parameters:
      resource:
        description: resource class to use
        type: string
        default: medium

    executor: linux
    resource_class: << parameters.resource >>
    steps:
    - checkout
    - go/install:
        version: "1.18"
    - run: sudo apt-get update
    - run: sudo apt-get install --yes libsodium-dev
    - run: make release-binary

  build-universal-binary:
    executor: macos
    steps:
    - checkout
    - go/install:
        version: "1.18"
    - run: brew install pkg-config
    - run: make dist/garotate-darwin-universal

workflows:
  all-binaries:
    when:
      equal: [ << pipeline.git.branch >>, 'circleci' ]

    jobs:
    - build-binary:
        matrix:
          parameters:
            resource: [ medium, medium.arm64 ]

    - build-universal-binary
