version: 2.1

orbs:
  go: circleci/go@1.7.1

executors:
  linux:
    docker:
      - image: golang:1.18

  macos:
    macos:
      xcode: 13.3.1

# WIP
#   notifiy:
#     docker:
#       - image: golang:1.18

jobs:
  build-binary:
    executor: linux
    environment:
      TAG: << pipeline.git.tag >>
    steps:
    - checkout
    - run: apt-get update
    - run: apt-get install --yes awscli
    - run: make upload-release-binary S3BUCKET=$TAG TARGET_ARCH=amd64
    - run: make upload-release-binary S3BUCKET=$TAG TARGET_ARCH=arm64
    - run: make upload-release-binary S3BUCKET=$TAG TARGET_OS=windows TARGET_ARCH=amd64
    - run: make upload-release-binary S3BUCKET=$TAG TARGET_OS=windows TARGET_ARCH=arm64
    - run: make upload-release-binary S3BUCKET=$TAG TARGET_OS=windows TARGET_ARCH=386

  build-universal-binary:
    executor: macos
    environment:
      TAG: << pipeline.git.tag >>
    steps:
    - checkout
    - go/install:
        version: "1.18"
    - run: brew install awscli || true
    - run: make upload-release-binary-universal S3BUCKET=$TAG

# WIP
#   notify-github-to-release:
#     executor: notify
#     steps:
#     - checkout
#     - run: wget https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.deb
#     - run: dpkg -i gh_2.9.0_linux_amd64.deb
#     - run: gh ...

workflows:
  all-binaries:
    jobs:
    - build-binary:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^release-(\d+\.\d+(-[a-z]+\d+))$/
    - build-universal-binary:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^release-(\d+\.\d+(-[a-z]+\d+))$/

# WIP
#     - notify-github-to-release:
#         requires:
#         - build-binary
#         - build-universal-binary
