---
on:
  push:
    tags:
    - 'v*'

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install --yes libsodium-dev
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - run: go mod download
    - run: go test -race -v ./...

  publish-garotate-binaries:
    needs: [ release-test ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          asset_name: garotate-linux-x86_64
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install --yes libsodium-dev
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: make release-binary
    - uses: release-drafter/release-drafter@v5
      with:
        config-name: .github/release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: dirst/${{ matrix.asset_name }}

  docker:
    needs: [ release-test ]
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/metadata-action@v2
      id: meta
      with:
        images: zostay/garotate
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.doutputs.labels }}
