---
on:
  push:
    tags:
    - 'v*'

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install --yes libsodium-dev
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - run: go mod download
    - run: go test -race -v ./...

  publish-garotate-binaries:
    needs: [ release-test ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          artifact_name: garotate-linux-amd64
          asset_name: garotate-linux-amd64
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: make release-binary
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
    
  docker:
    needs: [ release-test ]
    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/metadata-action@v2
      id: meta
      with:
        images: zostay/garotate
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.doutputs.labels }}
