---
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - run: go mod download
    - run: go build ./...
    - run: go test ./...

  docker-smoke:
    runs-on: ubuntu-latest
    steps:
      uses: docker/build-push-action@v2
      with:
        push: false
