---
on:
  push:

jobs:
  quicktest:
    steps:
    - run: echo ${{ secrets.TEST }}

  test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install --yes libsodium-dev
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - run: go mod download
    - run: go build -race ./...
    - run: go test -race -v ./...

  docker-smoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        push: false
